In [1]:
import torch

In [ ]:
# 요소별 산술 연산

a = torch.FloatTensor([[1, 2],
                        [3, 4]])
b = torch.FloatTensor([[2, 2],
                        [3, 3]])

print(a + b)    # 요소별 덧셈
print(a - b)    # 요소별 뺄셈
print(a * b)    # 요소별 곱셈
print(a / b)    # 요소별 나눗셈
print(a ** b)   # 요소별 거듭제곱
print(a == b)   # 요소별 값 비교 (같으면 True, 다르면 False)
print(a != b)   # 요소별 값 비교 (다르면 True, 같으면 False)

tensor([[3., 4.],
        [6., 7.]])
tensor([[-1.,  0.],
        [ 0.,  1.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[0.5000, 1.0000],
        [1.0000, 1.3333]])
tensor([[ 1.,  4.],
        [27., 64.]])
tensor([[False,  True],
        [ True, False]])
tensor([[ True, False],
        [False,  True]])


In [ ]:
# 인플레이스 연산

a = torch.FloatTensor([[1, 2],
                        [3, 4]])
print(a)                # 원래 텐서 출력
print(a.mul(b))         # 곱셈 결과를 새로운 텐서로 반환 -> a는 변하지 않음
print(a)                # 원래 텐서 그대로 유지
print(a.mul_(b))        # mul_처럼 함수명 뒤에 _가 붙으면 인플레이스 연산 -> 기존 텐서 a가 수정됨
print(a)                # 수정된 텐서 출력

tensor([[1., 2.],
        [3., 4.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])


In [ ]:
# 차원 축소 연산

x = torch.FloatTensor([[1, 2],
                        [3, 4]])

print(x.sum())          # 전체 요소의 합
print(x.mean())         # 전체 요소의 평균

print(x.sum(dim=0))     # 열(column) 기준 합
print(x.sum(dim=-1))    # 행(row) 기준 합

tensor(10.)
tensor(2.5000)
tensor([4., 6.])
tensor([3., 7.])


In [ ]:
# 텐서 + 스칼라: 모든 요소에 스칼라 값이 더해짐 (브로드캐스팅)

x = torch.FloatTensor([[1, 2],
                        [3, 4]])
y = 1

z = x + y
print(z)            # 각 요소에 1이 더해짐 -> [[2, 3], [4, 5]]
print(z.size())     # 결과 텐서의 크기: [2, 2]

tensor([[2., 3.],
        [4., 5.]])
torch.Size([2, 2])


In [ ]:
# 텐서 + 벡터: 벡터가 각 행에 브로드캐스팅되어 더해짐

x = torch.FloatTensor([[1, 2],
                        [3, 4]])
y = torch.FloatTensor([3,
                        5])

print(x.size())     # 텐서 x의 크기: [2, 2]
print(y.size())     # 벡터 y의 크기: [2]

z = x + y
print(z)            # y가 각 열에 맞게 브로드캐스팅됨 -> [[1 + 3, 2 + 5], [3 + 3, 4 + 5]] = [[4, 7], [6, 9]]
print(z.size())     # 결과 텐서의 크기: [2, 2]

torch.Size([2, 2])
torch.Size([2])
tensor([[4., 7.],
        [6., 9.]])
torch.Size([2, 2])


In [ ]:
# 텐서 + 텐서: 서로 다른 크기의 텐서 간 브로드캐스팅 연산

x = torch.FloatTensor([[1, 2]])     # 크기: [1, 2]
y = torch.FloatTensor([[3],
                        [5]])       # 크기: [2, 1]

print(x.size())     # 텐서 x의 크기: [1, 2]
print(y.size())     # 텐서 y의 크기: [2, 1]

z = x + y
print(z)            # x과 y가 서로 브로드캐스팅됨 -> [[1 + 3, 2 + 3], [1 + 5, 2 + 5]] = [[4, 5], [6, 7]]
print(z.size())     # 결과 텐서의 크기: [2, 2]

torch.Size([1, 2])
torch.Size([2, 1])
tensor([[4., 5.],
        [6., 7.]])
torch.Size([2, 2])
