In [1]:
import torch

In [ ]:
# view 함수: 텐서의 모양(Shape)을 바꾸는 함수

x = torch.FloatTensor([[[1, 2],
                        [3, 4]],
                        [[5, 6],
                        [7, 8]],
                        [[9, 10],
                        [11, 12]]])
print(x.size())         # 원래 크기: [3, 2, 2]
print(x.view(12))       # 1D 벡터로 변환 -> [12]
print(x.view(3, 4))     # 2D 텐서로 재구성 -> [3, 4]
print(x.view(3, 1, 4))  # 3D 텐서로 재구성 -> [3, 1, 4]
print(x.view(-1))       # 전체 요소 수를 기준으로 1D로 변환 -> [12]
print(x.view(3, -1))    # 첫 차원은 3, 나머지는 자동 계산 -> [3, 4]
print(x.view(-1, 1, 4)) # 마지막 두 차원 지정, 나머지는 자동 계산 -> [3, 1, 4]


torch.Size([3, 2, 2])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])


In [ ]:
# squeeze 함수: 크기가 1인 차원을 제거

x = torch.FloatTensor([[[1, 2],
                        [3, 4]]])
print(x.size())                 # 원래 크기: [1, 2, 2]
print(x.squeeze())              # 모든 크기 1인 차원 제거 -> [2, 2]
print(x.squeeze().size())       # 결과 크기: [2, 2]
print(x.squeeze(0).size())      # 0번 차원만 제거 -> [2, 2]
print(x.squeeze(1).size())      # 1번 차원은 2이므로 제거되지 않음 -> [1, 2, 2]

torch.Size([1, 2, 2])
tensor([[1., 2.],
        [3., 4.]])
torch.Size([2, 2])
torch.Size([2, 2])
torch.Size([1, 2, 2])


In [ ]:
# unsqueeze 함수: 크기 1인 차원을 추가

x = torch.FloatTensor([[1, 2],
                        [3, 4]])
print(x.size())                 # 원래 크기: [2, 2]
print(x.unsqueeze(0).size())    # 0번 차원에 1 추가 -> [1, 2, 2]
print(x.unsqueeze(1).size())    # 1번 차원에 1 추가 -> [2, 1, 2]
print(x.unsqueeze(2).size())    # 2번 차원에 1 추가 -> [2, 2, 1]

torch.Size([2, 2])
torch.Size([1, 2, 2])
torch.Size([2, 1, 2])
torch.Size([2, 2, 1])
