In [1]:
import torch

In [ ]:
# 인덱싱과 슬라이싱: 텐서에서 원하는 위치의 데이터를 추출하는 방법

x = torch.FloatTensor([[[1, 2],
                        [3, 4]],
                        [[5, 6],
                        [7, 8]],
                        [[9, 10],
                        [11, 12]]])
print(x.size())             # 크기: [3, 2, 2]
print(x[0])                 # 첫 번째 2 x 2 텐서 추출
print(x[-1])                # 마지막 2 x 2 텐서 추출
print(x[:, 0])              # 각 텐서의 첫 번째 행만 추출 -> 크기: [3, 2]
print(x[1:2, 1:, :])        # 두 번째 텐서의 두 번째 행만 추출 -> 크기: [1, 1, 2]

torch.Size([3, 2, 2])
tensor([[1., 2.],
        [3., 4.]])
tensor([[ 9., 10.],
        [11., 12.]])
tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]])
tensor([[[7., 8.]]])


In [3]:
# split 함수: 텐서를 특정 크기로 나눔

x = torch.FloatTensor(10, 4)
splits = x.split(4, dim=0)          # 0번 차원을 기준으로 4개씩 나눔 -> 결과는 [4, 4], [4, 4], [2, 4]

for s in splits:
    print(s.size())                 # 각 조각의 크기 출력

torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([2, 4])


In [4]:
# chunk 함수: 텐서를 지정한 개수만큼 균등하게 나눔 (크기가 다를 수도 있음)

x = torch.FloatTensor(8, 4)
chunks = x.chunk(3, dim=0)      # 3개로 나눔 -> [3, 4], [3, 4], [2, 4]

for c in chunks:
    print(c.size())             # 각 청크의 크기 출력

torch.Size([3, 4])
torch.Size([3, 4])
torch.Size([2, 4])


In [ ]:
# index_select 함수: 주어진 인덱스를 기준으로 특정 차원에서 선택

x = torch.FloatTensor([[[1, 1],
                        [2, 2]],
                        [[3, 3],
                        [4, 4]],
                        [[5, 5],
                        [6, 6]]])
indice = torch.LongTensor([2, 1])           # 선택할 인덱스

print(x.size())                             # 원본 텐서 크기: [3, 2, 2]
y = x.index_select(dim=0, index=indice)     # 0번 차원에서 2번, 1번 순으로 선택
print(y)
print(y.size())                             # 선택된 결과 크기: [2, 2, 2]


torch.Size([3, 2, 2])
tensor([[[5., 5.],
         [6., 6.]],

        [[3., 3.],
         [4., 4.]]])
torch.Size([2, 2, 2])


In [6]:
# cat 함수: 여러 텐서를 특정 차원에서 연결

x = torch.FloatTensor([[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]])
y = torch.FloatTensor([[10, 11, 12],
                        [13, 14, 15],
                        [16, 17, 18]])
print(x.size(), y.size())           # 둘 다 크기: [3, 3]

z = torch.cat([x, y], dim=0)
print(z)
print(z.size())                     # 행 방향으로 연결 -> 크기: [6, 3]

z = torch.cat([x, y], dim=1)
print(z)
print(z.size())                     # 열 방향으로 연결 -> 크기: [3, 6]

torch.Size([3, 3]) torch.Size([3, 3])
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]])
torch.Size([6, 3])
tensor([[ 1.,  2.,  3., 10., 11., 12.],
        [ 4.,  5.,  6., 13., 14., 15.],
        [ 7.,  8.,  9., 16., 17., 18.]])
torch.Size([3, 6])


In [7]:
# stack 함수: 새로운 차원을 추가하여 텐서들을 쌓음

z = torch.stack([x, y])
print(z)
print(z.size())                     # 0번 차원에 쌓기 -> 크기: [2, 3, 3]

z = torch.stack([x, y], dim=1)
print(z)
print(z.size())                     # 1번 차원에 쌓기 -> 크기: [3, 2, 3]

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])
torch.Size([2, 3, 3])
tensor([[[ 1.,  2.,  3.],
         [10., 11., 12.]],

        [[ 4.,  5.,  6.],
         [13., 14., 15.]],

        [[ 7.,  8.,  9.],
         [16., 17., 18.]]])
torch.Size([3, 2, 3])
