In [1]:
import torch
import torch.nn as nn

In [2]:
# 사용자 정의 선형 계층 클래스 정의

class MyLinear(nn.Module):

    def __init__(self, input_dim=3, output_dim=2):
        # 입력 차원과 출력 차원 설정
        self.input_dim = input_dim
        self.output_dim = output_dim

        super().__init__() # nn.Module 초기화

        # 가중치 W와 편향 b를 학습 가능한 파라미터로 등록
        self.W = nn.Parameter(torch.FloatTensor(input_dim, output_dim))
        self.b = nn.Parameter(torch.FloatTensor(output_dim))

    def forward(self, x):
        # 선형 변환 수행: y = Wx + b
        y = torch.matmul(x, self.W) + self.b
        return y

In [3]:
# 테스트용 데이터
W = torch.FloatTensor([i for i in range(1, 7)]).reshape(3, 2)
b = torch.FloatTensor([2, 2])
x = torch.FloatTensor(4, 3)

In [ ]:
linear = MyLinear(3, 2)     # MyLinear 클래스 인스턴스 생성
y = linear(x)               # 입력 데이터를 선형 계층에 통과시킴

# 학습 가능한 파라미터 출력 (가중치 W와 편향 b)
for p in linear.parameters():
    print(p)

Parameter containing:
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]], requires_grad=True)
Parameter containing:
tensor([7.9688e+37, 4.5825e-41], requires_grad=True)


In [ ]:
#torch.nn에 구현된 선형 계층 사용하기

linear = nn.Linear(3, 2)
y = linear(x)

for p in linear.parameters():
    print(p)

Parameter containing:
tensor([[ 0.3095, -0.3668, -0.0789],
        [ 0.2531,  0.5505,  0.4001]], requires_grad=True)
Parameter containing:
tensor([-0.2550, -0.2457], requires_grad=True)
