In [1]:
import torch
import torch.nn.functional as F

In [ ]:
target = torch.linspace(0.1, 0.9, steps=9).reshape(3, 3)
x = torch.rand_like(target)
x.requires_grad = True # x에 대해 미분을 수행할 수 있도록 설정
print(x)

tensor([[0.5965, 0.6040, 0.8874],
        [0.4241, 0.7518, 0.4177],
        [0.5110, 0.9830, 0.5830]], requires_grad=True)


In [ ]:
# 초기 loss 계산: MSE 사용

loss = F.mse_loss(x, target)
print(loss)

tensor(0.1135, grad_fn=<MseLossBackward0>)


In [ ]:
# 학습 파라미터 설정
threshold = 1e-5    # loss가 이 값 이하로 떨어지면 학습 중단
lr = 1.0            # 학습률(Learning Rate)
iter_cnt = 0        # 반복 횟수 카운트

# loss가 threshold보다 클 동안 반복 학습
while loss > threshold:
    iter_cnt += 1
    loss.backward()                 # 손실 함수에 대해 x를 기준으로 미분

    x = x - lr * x.grad             # 경사 하강법으로 파라미터 업데이트
    x.detach_()                     # 그래프 끊기 (이전 그래프와 분리)
    x.requires_grad_(True)          # 새로 업데이트된 x에 대해 다시 미분 가능 설정

    loss = F.mse_loss(x, target)    # 업데이트된 x로 새로운 loss 계산

    # 반복 횟수, 손실 값, x 출력
    print('%d-th Loss: %.4e' % (iter_cnt, loss))
    print(x)

1-th Loss: 6.8677e-02
tensor([[0.4862, 0.5142, 0.7569],
        [0.4188, 0.6959, 0.4582],
        [0.5530, 0.9423, 0.6535]], requires_grad=True)
2-th Loss: 4.1545e-02
tensor([[0.4004, 0.4444, 0.6553],
        [0.4146, 0.6523, 0.4897],
        [0.5857, 0.9107, 0.7082]], requires_grad=True)
3-th Loss: 2.5132e-02
tensor([[0.3336, 0.3901, 0.5764],
        [0.4114, 0.6185, 0.5142],
        [0.6111, 0.8861, 0.7509]], requires_grad=True)
4-th Loss: 1.5203e-02
tensor([[0.2817, 0.3479, 0.5150],
        [0.4088, 0.5922, 0.5333],
        [0.6308, 0.8670, 0.7840]], requires_grad=True)
5-th Loss: 9.1971e-03
tensor([[0.2413, 0.3150, 0.4672],
        [0.4069, 0.5717, 0.5481],
        [0.6462, 0.8521, 0.8098]], requires_grad=True)
6-th Loss: 5.5637e-03
tensor([[0.2099, 0.2894, 0.4300],
        [0.4053, 0.5557, 0.5596],
        [0.6582, 0.8405, 0.8298]], requires_grad=True)
7-th Loss: 3.3657e-03
tensor([[0.1855, 0.2696, 0.4011],
        [0.4042, 0.5434, 0.5686],
        [0.6675, 0.8315, 0.8454]], requi